//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateOrders
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConcentratorSport2000Entities : DbContext
    {
        public ConcentratorSport2000Entities()
            : base("name=ConcentratorSport2000Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderAttributeValueBit> OrderAttributeValueBit { get; set; }
        public virtual DbSet<OrderAttributeValueDateTime> OrderAttributeValueDateTime { get; set; }
        public virtual DbSet<OrderAttributeValueDecimal> OrderAttributeValueDecimal { get; set; }
        public virtual DbSet<OrderAttributeValueImage> OrderAttributeValueImage { get; set; }
        public virtual DbSet<OrderAttributeValueInt> OrderAttributeValueInt { get; set; }
        public virtual DbSet<OrderAttributeValueVarchar> OrderAttributeValueVarchar { get; set; }
        public virtual DbSet<OrderLine> OrderLine { get; set; }
        public virtual DbSet<OrderLineAttributeValueBit> OrderLineAttributeValueBit { get; set; }
        public virtual DbSet<OrderLineAttributeValueDateTime> OrderLineAttributeValueDateTime { get; set; }
        public virtual DbSet<OrderLineAttributeValueDecimal> OrderLineAttributeValueDecimal { get; set; }
        public virtual DbSet<OrderLineAttributeValueInt> OrderLineAttributeValueInt { get; set; }
        public virtual DbSet<OrderLineAttributeValueVarchar> OrderLineAttributeValueVarchar { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddress { get; set; }
        public virtual DbSet<Address> Address { get; set; }
    }
}
