//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int OrderLineID { get; set; }
        public string Remarks { get; set; }
        public int OrderID { get; set; }
        public string CustomerOrderLineNr { get; set; }
        public string CustomerOrderNr { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Quantity { get; set; }
        public bool isDispatched { get; set; }
        public Nullable<int> DispatchedToVendorID { get; set; }
        public Nullable<int> VendorOrderNumber { get; set; }
        public string Response { get; set; }
        public Nullable<bool> CentralDelivery { get; set; }
        public string CustomerItemNumber { get; set; }
        public string WareHouseCode { get; set; }
        public bool PriceOverride { get; set; }
        public string LotLocation { get; set; }
        public string LotNumber { get; set; }
        public Nullable<System.DateTime> PromisedShipDate { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public string CustomIdentifier { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
