//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderLine = new HashSet<OrderLine>();
        }
    
        public int OrderID { get; set; }
        public string Document { get; set; }
        public int ConnectorID { get; set; }
        public bool IsDispatched { get; set; }
        public Nullable<System.DateTime> DispatchToVendorDate { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public Nullable<bool> isDropShipment { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ShipToCustomerID { get; set; }
        public string CustomerOrderReference { get; set; }
        public string EdiVersion { get; set; }
        public string BSKIdentifier { get; set; }
        public string WebSiteOrderNumber { get; set; }
        public string PaymentTermsCode { get; set; }
        public Nullable<bool> BackOrdersAllowed { get; set; }
        public string RouteCode { get; set; }
        public string HoldCode { get; set; }
        public Nullable<int> SoldToCustomerID { get; set; }
        public bool HoldOrder { get; set; }
        public Nullable<int> ShipToAddressID { get; set; }
        public int PaymentInstrumentID { get; set; }
        public string FreightHandlingCode { get; set; }
        public string Carrier { get; set; }
        public string DocumentType { get; set; }
        public string DeliveryInstructions1 { get; set; }
        public string DeliveryInstructions2 { get; set; }
        public Nullable<System.DateTime> PromisedShipDate { get; set; }
        public string CustomIdentifier { get; set; }
        public Nullable<int> ConsigneeCustomerID { get; set; }
        public int OrderType { get; set; }
        public string TakenBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLine { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual Customer Customer2 { get; set; }
        public virtual Address Address { get; set; }
    }
}
