//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAttributeValueImage
    {
        public int AttributeValueID { get; set; }
        public int AttributeID { get; set; }
        public int ObjectID { get; set; }
        public int LanguageID { get; set; }
        public byte[] Value { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    }
}
